### ISSUE TITLE
error with multiple random parts in `wbm()`

### ISSUE THREAD

**Issue by strengejacke** [jacob-long/panelr#14]
[You said](https://twitter.com/jacobandrewlong/status/1131174980144828416) it is supposed to work, but I get an error here. Maybe I misspecified the formula?

``` r
library(panelr)
load(url("https://github.com/strengejacke/mixed-models-snippets/raw/master/example.RData"))
pd <- panel_data(d, id = ID, wave = time)
m <- wbm(QoL ~ x_tv | age + z1_ti + z2_ti + time  | (time | ID) + (x_tv | ID), data = pd)
#> Error in parse(text = x, keep.source = FALSE): <text>:2:0: unexpected end of input
#> 1:  ~  `QoL` + `x_tv` + `age` + `z1_ti` + `z2_ti` + `time` + (`time` + `ID`) + (`x_tv`  +  imean(x_tv)
#>    ^
```

<sup>Created on 2019-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jacob-long** [comment]
Thanks for catching this — I should have been testing to see if these models would run. It failed in a surprising way, but it was pretty straightforward to fix.
