### ISSUE TITLE
[ method

### ISSUE THREAD

**Issue by hadley** [jacob-long/panelr#28]
When you use `[` with a single argument to select a column it returns the columns that you select, along with the `wave` and `id` variables:

``` r
library(panelr)

data("WageData")
wages <- panel_data(WageData, id = id, wave = t)

length(wages[3])
#> [1] 3
```

<sup>Created on 2020-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This causes problems with dev tidyr (which I've hacked around so I can push out a release soon), and in general is likely to cause problems across the tidyverse because we expect `length(df[x])` to equal `length(x)` (when `x` is an integer or character vector).

**Comment by hadley** [comment]
Making this hack fixes your package, but breaks another package (amt), so I'm in the process of reconsidering it.

**Comment by hadley** [comment]
I have found a different hack that should make every package happy :smile:

**Comment by jacob-long** [comment]
Seems like I have it working as before now. Had to create several new methods (e.g., `[<-.panel_data`) because a number of routine operations were causing `panel_data` objects to lose their class and revert to grouped tibbles.
