### ISSUE TITLE
CRAN Check Failure for Upcoming broom Release

### ISSUE THREAD

**Issue by simonpcouch** [jacob-long/panelr#30]
Hi there! The broom dev team just ran reverse dependency checks on the upcoming broom 0.7.0 release and found new errors/test failures for the CRAN version of this package. I've pasted the results below, which seem to result from our planned deprecation of tidiers for mixed models.

*   checking examples ... ERROR
    ```
    Running examples in ‘panelr-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: tidy.wbm
    > ### Title: Tidy methods for 'wbm' models
    > ### Aliases: tidy.wbm glance.wbm glance.summ.wbm tidy.summ.wbm
    > 
    > ### ** Examples
    > 
    > data("WageData")
    > wages <- panel_data(WageData, id = id, wave = t)
    > model <- wbm(lwage ~ lag(union) + wks, data = wages)
    > if (requireNamespace("broom")) {
    +   broom::tidy(model)
    + }
    Error: No tidy method for objects of class lmerMod
    Execution halted
    ```

*   checking tests ...
    ```
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      > 
      > test_check("panelr")
      [31m──[39m [31m1. Error: tidy works (@test-utils.R#341) [39m [31m───────────────────────────────────[39m
      No tidy method for objects of class lmerMod
      [1mBacktrace:[22m
      [90m 1. [39mtestthat::expect_is(tidy.wbm(wb), "tbl_df")
      [90m 4. [39mpanelr:::tidy.wbm(wb)
      [90m 6. [39mbroom:::tidy.default(...)
      
      ══ testthat results  ═══════════════════════════════════════════════════════════
      [ OK: 291 | SKIPPED: 0 | WARNINGS: 2436 | FAILED: 1 ]
      1. Error: tidy works (@test-utils.R#341) 
      
      Error: testthat unit tests failed
      Execution halted
    ```

Functions and methods for tidying mixed models now live in the `broom.mixed` package.

We hope to submit this new version of the package to CRAN in the coming weeks. If you encounter any problems fixing these issues, please feel free to reach out!🙂

**Comment by hannes101** [comment]
This is probably the reason, why it was removed from CRAN, correct?

**Comment by simonpcouch** [comment]
@hannes101 I'm not sure what you're referring to. Was the `panelr` package recently removed from CRAN? The fix should be as sample as switching out `broom::` for `broom.mixed::`. We've yet to receive final word on our CRAN submission.

**Comment by hannes101** [comment]
Ok, sorry for not providing more background and probably mixing things up.
 https://cran.r-project.org/web/packages/panelr/index.html states that it was removed from CRAN, so I thought this issue was the reason.

**Comment by jacob-long** [comment]
The main issue was test failures caused by recent releases of `tidyverse` packages. I actually was not aware it had been removed until @hannes101 commented here. I will be submitting back to CRAN today.
