### ISSUE TITLE
Any plan to reupload to CRAN?

### ISSUE THREAD

**Issue by NickCH-K** [jacob-long/panelr#40]
Hi there,

Since **tibble** updated I'll need to do an update to **pmdplyr** soon. Right now I have **panelr** in the Suggests, so `pmdplyr::panel_convert()` can convert to/from `panel_data` objects. But it looks like **panelr** has been removed from CRAN. Is there a plan to re-upload it? If not I may need to remove the `panel_data` functionality from `pmdplyr::panel_convert()` on my next upload.

Thanks!

**Comment by NickCH-K** [comment]
It looks like the problem is that **clubSandwich** has been removed from CRAN as well. But they appear to have [resubmitted fairly recently](https://github.com/jepusto/clubSandwich/commit/800fcc6f09c188dfea42a7152b4f478564e379fc), so once that's up (I imagine) **panelr** can go back up too.

**Comment by jacob-long** [comment]
Yes, I plan to resubmit in the next few days or sooner. It was indeed `clubSandwich`'s removal from CRAN that has twice led to `panelr` being archived.
