### ISSUE TITLE
Error in compiling Stan model

### ISSUE THREAD

**Issue by giannilmbd** [jacob-long/panelr#43]
Hi,
thanks for this great package.
Trying the wbm_stan I encountered a compilation error. 
**I'm working on this machine/R version**
`platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.4                         
year           2021                        
month          02                          
day            15                          
svn rev        80002                       
language       R                           
version.string R version 4.0.4 (2021-02-15)
nickname       Lost Library Book `
**This is the command** (data attached)
`AE<-c("US","DE","CA","GB","NZ","AU","SE","CH","IT","FR") 
AE<-AE[order(AE)]
EME<-c("IN","MY","ZA","TR","TH","SG","ID","CN","BR","MX","KR")
EME<-EME[EME %>% order]

pandat<-panel_data(dt_[dt_$cc%in%c(AE[!AE%in%"US"],EME),],id=cc,wave=year)

library(brms)

model<-wbm_stan(formula=excess_ret10~lag(Dus10y)+lag(core_inflation),data=pandat,model="within",min.waves = 5,scale=T)`

[data4wbm_bug.xlsx](https://github.com/jacob-long/panelr/files/6125520/data4wbm_bug.xlsx)
**and this is the error**

>  Error in compileCode(f, code, language = language, verbose = verbose) : 
> 
>   /home/gianni/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/src/stan/model/model_base_crtp.hpp:149:20:   required from here/home/gianni/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/DenseCoeffsBase.h:55:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type’ {aka ‘__vector(2) double’} [-Wignored-attributes]/usr/bin/ld: /usr/lib/R/site-library/rstan/lib//libStanServices.a(stan_fit.o): relocation R_X86_64_PC32 against undefined hidden symbol `_ZTCN5boost10wrapexceptINS_4math14rounding_errorEEE0_NS_16exception_detail10clone_implINS4_19error_info_injectorIS2_EEEE' can not be used when making a shared object/usr/bin/ld: final link failed: bad valuecollect2: error: ld returned 1 exit statusmake: *** [/usr/share/R/share/make/shlib.mk:10: file22b175fc6cf5f.so] Error 1
> In addition: Warning messages:
> 1: In jtools::gscale(x = scale_names, data = data, n.sd = 1, binary.inputs = "0/1") :
>   The x argument is deprecated. Pass column names to the vars argument.
> 2: Argument 'save_ranef' is deprecated. Please use argument 'group' in function 'save_pars()' instead. 
> Error in sink(type = "output") : invalid connection

Is this a known problem?
Thanks
Gianni

**Comment by jacob-long** [comment]
I'm sorry, this actually compiles on my machine so I think it may be specific to the R/Stan/compiler installation. I won't be of a lot of help troubleshooting that kind of thing.
