### ISSUE TITLE
Avoid `tibble::trunc_mat()`

### ISSUE THREAD

**Issue by krlmlr** [jacob-long/panelr#55]
I would like to remove the `trunc_mat()` function entirely from the tibble package, as much better alternatives now exist. See, e.g., <https://pillar.r-lib.org/articles/extending.html>.

As far as I can tell, panelr is the only function still using `trunc_mat()` . Would you mind sending an update to CRAN? Happy to help.

**Comment by jacob-long** [comment]
Not a problem, looks like I've got a working fix thanks to the documentation you shared. I should have an update to CRAN before long.
