### ISSUE TITLE
Available without CRAN

### ISSUE THREAD

**Issue by cgnguyen** [jacob-long/panelr#58]
Unfortunately, the package is currently not available from CRAN anymore. Are there any other sources or is there any chance it will get back on CRAN? 

Thank you for the super helpful package!

**Comment by jacob-long** [comment]
Hi Christoph, I'm working to get it back on CRAN. There was a small issue that has taken a lot of time to resolve. In the meantime, you can download the version on Github via:

```r
remotes::install_github("jacob-long/panelr")
```
